name: trf
description: >
  Wrapper for Tandem Repeats Finder (TRF), a tool to identify tandem repeats in DNA sequences,
  enabling easy integration into Snakemake workflows.
url: https://tandem.bu.edu/trf/home
authors:
  - Muhammad Rohan Ali Asmat
input:
  - fasta: DNA sequence file in FASTA format to be analyzed by Tandem Repeats Finder.
output:
  - dat: Path to the repeat table file (*.dat) with repeat details including location, size, copy number, and nucleotide content.
  - align: Path to the alignment file (*.align) showing how repeat units align to a consensus sequence.
  - mask: Path to the masked sequence file (*.mask) generated if the `-m` flag is used (optional).
  - html: Path to the HTML report file (*.html), generated only if the `-h` or related flag is passed (optional).
params:
  match: "Match weight (default: 2)"
  mismatch: "Mismatch penalty (default: 7)"
  delta: "Indel penalty (default: 7)"
  pm: "Match probability percentage (default: 80)"
  pi: "Indel probability percentage (default: 10)"
  minscore: "Minimum alignment score to report (default: 50)"
  maxperiod: "Maximum period size to report (default: 500)"
  extra: "Optional command-line flags to pass to Tandem Repeats Finder (TRF). These flags are appended after the 7 required numeric parameters. Supported flags (default state in parentheses): -m (off, generate masked sequence file), -f (off, include flanking sequence), -d (on, produce .dat file), -h (off, suppress HTML output), -r (on, enable redundancy filtering), -l <n> (default 20 Mbp, set max tandem repeat size), -ngs (off, compact output for NGS), -u (off, show usage), -v (off, show version). Provide flags as a quoted string, e.g., '-d -h'."
notes: >
  Command template used:
  trf <input.fasta> <match> <mismatch> <delta> <pm> <pi> <minscore> <maxperiod> <extra>

  If one or more numeric parameters (e.g., match, mismatch) are not provided,
  the wrapper will automatically substitute the default values recommended by TRF, as listed above.

  Flags (extra) are optional and can be specified using the 'extra' param (e.g., '-d -h').
  No default flags are added unless explicitly set by the user.

  GitHub Repository: https://github.com/Benson-Genomics-Lab/TRF  
  Bioconda Package: https://prefix.dev/channels/bioconda/packages/trf
